const INVOICE = "INVOICE";
const QUOTE = "QUOTE";
const PURCHASE_AGREEMENT = "PURCHASE AGREEMENT";
const TO = "TO";
const FROM = "FROM";
const OPEN = "OPEN";
const DOWNLOAD = "DOWNLOAD";
const PRINT = "PRINT";

export { INVOICE, QUOTE, PURCHASE_AGREEMENT, TO, FROM, OPEN, DOWNLOAD, PRINT };